channels:
- conda-forge
dependencies:
- python=3.8.5
- pip<=20.2.4
- pip:
  - mlflow==2.10.2
  - click==7.1.2
  - cloudpickle==1.6.0
  - colorama==0.4.4
  - cytoolz==0.11.0
  - distributed==2.30.1
  - fsspec==2023.12.2
  - lightgbm==3.3.5
  - matplotlib==3.3.2
  - numexpr==2.7.1
  - numpy==1.23.5
  - packaging==23.2
  - pandas==1.1.3
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
